---
title: "DDD manuscript"
author: "Nathalie Jreidini"
date: '2022-09-27'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

1.  Animal dispersive movements play a key role in maintaining
    population dynamics, and density has been suggested to impact these movements
    either by driving or inhibiting them. Although the relationship between
    conspecific density and dispersal has been explored in various study systems,
    inconsistent results limit the formation of reliable general trends in terms of
    both the magnitude and the direction of density dependence.

2.  Here, we review empirical studies of animal dispersal in
    relation to conspecific density to examine the evidence for density-dependent
    dispersal among taxa and test whether reports of its occurrence are taxon-specific
    and/or biased by the methodology employed.

3.  We conducted a thorough review of the literature (2000 --
    2021) and found *k* = 81 empirical
    studies of amphibians, birds, fishes, invertebrates, mammals, or reptiles that had
    tested for a correlation between conspecific density and animal dispersal. We extracted
    categorical variables for taxonomic group, sex, age, migratory behavior, study
    design, density and dispersal metrics, as well as temporal and spatial scale, to
    test each of their correlation with the effect of density on dispersal (Pearson's
    *r*) using linear regressions and multilevel mixed-effect modelling. We
    tested for publication bias using funnel plots and trim-and-fill analysis to
    deduce asymmetry and examined heterogeneity among studies both across and
    within categories to ascertain the reliability of the results.

## Introduction

## Methods

## Results

## Discussion
